
package universidadgrupo69.vistas;


public class MenuOperaciones extends javax.swing.JFrame {

    /**
     * Creates new form MenuOperaciones
     */
    public MenuOperaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jmbBarraOPeraciones = new javax.swing.JMenuBar();
        jmAlumnos = new javax.swing.JMenu();
        jmiFormAlum = new javax.swing.JMenuItem();
        jmMaterias = new javax.swing.JMenu();
        jmiFormMaterias = new javax.swing.JMenuItem();
        jmAdministracion = new javax.swing.JMenu();
        jmiManejoInscripciones = new javax.swing.JMenuItem();
        jmiManipNotas = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiAlumXMateria = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jmAlumnos.setText("Alumnos");

        jmiFormAlum.setText("Formulaio Alumnos");
        jmiFormAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormAlumActionPerformed(evt);
            }
        });
        jmAlumnos.add(jmiFormAlum);

        jmbBarraOPeraciones.add(jmAlumnos);

        jmMaterias.setText("Materias");

        jmiFormMaterias.setText("Formulario Materias");
        jmiFormMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormMateriasActionPerformed(evt);
            }
        });
        jmMaterias.add(jmiFormMaterias);

        jmbBarraOPeraciones.add(jmMaterias);

        jmAdministracion.setText("Administracion");

        jmiManejoInscripciones.setText("Manejo de inscripciones");
        jmiManejoInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManejoInscripcionesActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmiManejoInscripciones);

        jmiManipNotas.setText("Manipulacion de notas");
        jmiManipNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManipNotasActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmiManipNotas);

        jmbBarraOPeraciones.add(jmAdministracion);

        jmConsultas.setText("Consultas");

        jmiAlumXMateria.setText("Alumnos por Materia");
        jmiAlumXMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlumXMateriaActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiAlumXMateria);

        jmbBarraOPeraciones.add(jmConsultas);

        jmSalir.setText("Salir");
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        jmbBarraOPeraciones.add(jmSalir);

        setJMenuBar(jmbBarraOPeraciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiFormAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormAlumActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        FormularioAlumnos fmAl = new FormularioAlumnos();
        fmAl.setVisible(true);
        jdpEscritorio.add(fmAl);
        jdpEscritorio.moveToFront(fmAl);
    }//GEN-LAST:event_jmiFormAlumActionPerformed

    private void jmiFormMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormMateriasActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        FormularioMaterias fmMa = new FormularioMaterias();
        fmMa.setVisible(true);
        jdpEscritorio.add(fmMa);
        jdpEscritorio.moveToFront(fmMa);
    }//GEN-LAST:event_jmiFormMateriasActionPerformed

    private void jmiManejoInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManejoInscripcionesActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        FormularioDeInscripcion fmDI = new FormularioDeInscripcion();
        fmDI.setVisible(true);
        jdpEscritorio.add(fmDI);
        jdpEscritorio.moveToFront(fmDI);
    }//GEN-LAST:event_jmiManejoInscripcionesActionPerformed

    private void jmiManipNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManipNotasActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        ActualizacionDeNotas acDN = new ActualizacionDeNotas();
        acDN.setVisible(true);
        jdpEscritorio.add(acDN);
        jdpEscritorio.moveToFront(acDN);
    }//GEN-LAST:event_jmiManipNotasActionPerformed

    private void jmiAlumXMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlumXMateriaActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        ConsultaDeAlumnosXMateria cAXM = new ConsultaDeAlumnosXMateria();
        cAXM.setVisible(true);
        jdpEscritorio.add(cAXM);
        jdpEscritorio.moveToFront(cAXM);
    }//GEN-LAST:event_jmiAlumXMateriaActionPerformed

    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jmSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOperaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmAlumnos;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmMaterias;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuBar jmbBarraOPeraciones;
    private javax.swing.JMenuItem jmiAlumXMateria;
    private javax.swing.JMenuItem jmiFormAlum;
    private javax.swing.JMenuItem jmiFormMaterias;
    private javax.swing.JMenuItem jmiManejoInscripciones;
    private javax.swing.JMenuItem jmiManipNotas;
    // End of variables declaration//GEN-END:variables
}
