
package TPDisenioClases3_0_SotoMartin_Leg26907;


public enum TipoCarroceria {
    CHASIS_RIGIDO_PCAMIONETA, 
    CHASIS_RETICULADO_PCAMIONETA,
    CHASIS_ANTIVUELCO__PCAMIONETA,
    CARROCERIA_CHAPA_MATRIZADA_PCAMIONETA,
    CHASIS_ESTANDAR_PAUTO,
    CHASIS_RETICULADO_PAUTO,
    CARROCERIA_CHAPA_MATRIZADA_PAUTO ,
    CUADRO_ESTANDAR_PMOTO, 
    CUADRO_RETICULADO_PMOTO; 
}
